name: youtube_feel_flutter
description: A new Flutter application.

version: 3.0.0+3

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+5
  firebase_messaging: ^5.0.2
  google_sign_in: ^4.0.7
  http: ^0.12.0+2
  pie_chart: ^1.3.0
  url_launcher: ^5.2.5
  flutter_inapp_purchase: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Simonetta
      fonts:
        - asset: fonts/Simonetta.ttf
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 700

  uses-material-design: true
  assets:
    - assets/
